Repository deavmi/birchwood, pull requests merged in 2023-03, with the labels that each got.

#14 Fix PING detection
  source/birchwood/client/receiver.d
Labels: bug

#17 Rfc2812
  source/birchwood/client/client.d
  source/birchwood/protocol/constants.d
Labels: enhancement, help wanted, good first issue

#21 Parameter parsing
  source/birchwood/client/client.d
  source/birchwood/protocol/messages.d
Labels: enhancement

#7 Add IRC formatting codes
  README.md
  source/birchwood/protocol/formatting.d
Labels: enhancement, good first issue
